org: '1256854590'
app: next
stage: dev
component: layer
name: next-layer
inputs:
  name: next-layer
  region: ap-guangzhou
  src:
    src: ../node_modules
    targetDir: /node_modules
  runtimes:
    - Nodejs12.16
